---
sudo: false
language: ruby
cache: bundler
bundler_args: --without system_tests
script: 'bundle exec rake validate lint spec'
notifications:
  email:
    - konstantin+travisci@linuxfoundation.org
matrix:
  fast_finish: true
  include:
    - rvm: 2.1.6
      env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
